---
- name: installing multiple package
  hosts: all
  become: true
  gather_facts: yes

  tasks:
  - name: multiple packages
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - git
      - wget
      - tree
      - make
      - telnet
      - gzip
