---
- name: uninstalling multiple packages
  hosts: all
  become: true
  gather_facts: yes

  tasks:
  - name: uninstall packages
    yum:
      name: [ 'git','tree' ]
      state: absent
      autoremove: yes

  - name: install packages
    yum:
      name: ['telnet', 'make', 'wget']
      state: installed
