---
- name: playbook to install apache tomcat
  hosts: webservers
  become: true
  gather_facts: yes
  vars_files:
    - tomcat_vars.yaml

  tasks:
    - name: install java-1.21*
      yum:
        name: java
        state: installed

    - name: downloading tomcat package
      get_url:
        url: "{{ tomcat_url }}"
        dest: /opt
        mode: 0755

    - name: extract packages
      unarchive:
        src: /opt/{{ tomcat_package }}.tar.gz
        dest: /opt
        remote_src: yes

    - name: change permissions on apache-tomcat dir
      file:
        path: /opt/{{ tomcat_package }}
        mode: 0755
        recurse: yes

    - name: creating link file for tomcat startup.sh
      file: 
        src: /opt/{{ tomcat_package }}/bin/startup.sh
        dest: /usr/local/bin/tomcat
        state: link

    - name: creating link file for tomcat shutdown.sh file
      file: 
        src: /opt/{{ tomcat_package }}/bin/shutdown.sh
        dest: /usr/local/bin/tomcatdown
        state: link

    - name: start the services
      command: nohup ./startup.sh
      args:
        chdir: /opt/{{ tomcat_package }}/bin/

